namespace SearchUsingDropDownList.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addDataToCityTable : DbMigration
    {
        public override void Up()
        {
            Sql(@"
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (1, 'Cairo')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2,'Giza')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Sixth of October')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Cheikh Zayed')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Hawamdiyah')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Al Badrasheen')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Saf')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Atfih')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Al Ayat')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Al-Bawaiti')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'ManshiyetAl Qanater')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Oaseem')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Kerdasa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Abu Nomros')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Kafr Ghati')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (2, 'Manshiyet Al Bakari')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (3, 'Alexandria')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (3, 'Burj Al Arab')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (3, 'New Burj Al Arab')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Banha')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Qalyub')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Shubra Al Khaimah')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Al Qanater Charity')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Khanka')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Kafr Shukr')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Tukh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Qaha')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Obour')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12, 'Khosous')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (12,'Shibin Al Qanater')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6, 'Damanhour')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Kafr El Dawar')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Rashid')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6, 'Edco')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6, 'Abu al-Matamir')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6, 'Abu Homs')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6, 'Delengat')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6, 'Mahmoudiyah')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6, 'Rahmaniyah')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Itai Baroud')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Housh Eissa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Shubrakhit')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Kom Hamada')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Badr')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'Wadi Natrun')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (6,  'New Nubaria')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23, 'Marsa Matrouh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23, 'El Hamam')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23, 'Alamein')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23,'Dabaa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23, 'Al-Nagila')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23, 'Sidi Brani')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23,  'Salloum')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (23, 'Siwa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'Damietta')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'New Damietta')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19, 'Ras El Bar')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'Faraskour')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'Zarqa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'alsaru')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'alruwda')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'Kafr El-Batikh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19, 'Azbet Al Burg')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19, 'Meet Abou Ghalib')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (19,  'Kafr Saad')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Mansoura')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Talkha')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Mitt Ghamr')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Dekernes')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Aga')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4,'Menia El Nasr')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Sinbillawin')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'El Kurdi')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Bani Ubaid')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4,'Al Manzala')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'tami alamdid')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'aljamalia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4,'Sherbin')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Mataria')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4,'Belqas')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4,'Meet Salsil')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Gamasa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Mahalat Damana')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (4, 'Nabroh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Kafr El Sheikh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22,'Desouq')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Fooh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22,'Metobas')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Burg Al Burullus')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22,'Baltim')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Masief Baltim')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Hamol')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22,'Bella')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Riyadh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Sidi Salm')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22,'Qellen')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (22, 'Sidi Ghazi')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8, 'Tanta')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8,  'Al Mahalla Al Kobra')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8,  'Kafr El Zayat')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8,  'Zefta')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8,  'El Santa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8, 'Qutour')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8, 'Basion')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (8,  'Samannoud')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Shbeen El Koom')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Sadat City')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Menouf')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Sars El-Layan')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Ashmon')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Al Bagor')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Quesna')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10,'Berkat El Saba')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10,'Tala')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (10, 'Al Shohada')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Zagazig')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (20, 'Al Ashr Men Ramadan')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Minya Al Qamh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (20,'Belbeis')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20,'Mashtoul El Souq')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Qenaiat')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Abu Hammad')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'El Qurain')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Hehia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (20,  'Abu Kabir')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Faccus')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (20,  'El Salihia El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (20,  'Al Ibrahimiyah')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (20,  'Deirb Negm')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Kafr Saqr')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Awlad Saqr')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'Husseiniya')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20, 'san alhajar alqablia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 20,'Manshayat Abu Omar')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (18,  'PorSaid')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 18, 'PorFouad')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (9, 'Ismailia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 9,'Fayed')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 9, 'Qantara Sharq')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (9,  'Qantara Gharb')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 9, 'El Tal El Kabier')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 9, 'Abu Sawir')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 9, 'Kasasien El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 14,'Suez')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 26, 'Arish')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 26, 'Sheikh Zowaid')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (26,  'Nakhl')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 26, 'Rafah')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 26, 'Bir al-Abed')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 26,'Al Hasana')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 21, 'Al Toor')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 21, 'Sharm El-Shaikh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES ( 21, 'Dahab')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (21,  'Nuweiba')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (21, 'Taba')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (21,  'Saint Catherine')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (21,  'Abu Redis')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (21,  'Abu Zenaima')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (21, 'Ras Sidr')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17,  'Bani Sweif')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17,  'Beni Suef El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17,  'Al Wasta')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17,'Naser')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17,  'Ehnasia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17, 'beba')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17,  'Fashn')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (17,  'Somasta')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (7, 'Fayoum')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (7,  'Fayoum El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (7, 'Tamiya')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (7, 'Snores')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (7,  'Etsa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (7, 'Epschway')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (7,  'Yusuf El Sediaq')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'Minya')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'Minya El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'El Adwa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'Magagha')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11,'Bani Mazar')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'Mattay')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'Samalut')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'Madinat El Fekria')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11, 'Meloy')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (11,'Deir Mawas')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16,'Assiut')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'Assiut El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'Dayrout')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'Manfalut')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'Qusiya')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16,'Abnoub')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'Abu Tig')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'El Ghanaim')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'Sahel Selim')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'El Badari')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (16, 'Sidfa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (13, 'El Kharga')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (13, 'Paris')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (13, 'Mout')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (13, 'Farafra')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (13, 'Balat')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (5,  'Hurghada')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (5,  'Ras Ghareb')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (5, 'Safaga')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (5,  'El Qusiar')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (5,  'Marsa Alam')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (5,  'Shalatin')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (5, 'Halaib')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'Sohag')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'Sohag El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27, 'Akhmeem')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'Akhmim El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'Albalina')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'El Maragha')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'almunshaa')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'Dar AISalaam')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'Gerga')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27,  'Jahina Al Gharbia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27, 'Saqilatuh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27, 'Tama')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (27, 'Tahta')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Qena')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'New Qena')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Abu Tesht')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Nag Hammadi')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Deshna')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Alwaqf')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25,'Qaft')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Naqada')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Farshout')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (25, 'Quos')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24, 'Luxor')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'New Luxor')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'Esna')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'New Tiba')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'Al ziynia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'Al Bayadieh')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'Al Qarna')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'Armant')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (24,'Al Tud')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Aswan')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Aswan El Gedida')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Drau')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Kom Ombo')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Nasr Al Nuba')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Kalabsha')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Edfu')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Al-Radisiyah')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Al Basilia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15,'Al Sibaeia')
INSERT INTO Cities (GovernorateID,CityNameEn) VALUES (15, 'Abo Simbl Al Siyahia');
  ");
        }
        
        public override void Down ()
        {
        }
    }
}
